linters-settings:
  misspell:
    locale: US

linters:
  enable:
    - errcheck
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unused
    - whitespace

issues:
  exclude:
    - "don't use an underscore in package name"
