version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
    - whitespace
  settings:
    misspell:
      locale: US
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - text: "don't use an underscore in package name"

formatters:
  enable:
    - goimports
