# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: lassie-bot-dog

before:
  hooks:
    - go mod tidy
builds:
  -
    flags:
      - -trimpath
    goos:
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  -
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: 'snapshot-{{ time "2006-01-02" }}'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  -
    # GOOS of the built binary that should be used.
    goos: linux
    # GOARCH of the built binary that should be used.
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - "geprog/lassie-bot-dog:{{ .Tag }}"
      - "geprog/lassie-bot-dog:latest"
