version: 2

# Make sure to check the documentation at http://goreleaser.com
project_name: lassie-bot-dog

before:
  hooks:
    - go mod tidy
builds:
  - flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
archives:
  - format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: 'snapshot-{{ time "2006-01-02" }}'
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
dockers_v2:
  - images:
      - "ghcr.io/geprog/lassie-bot-dog"
    tags:
      - "{{ .Tag }}"
      - "latest"
    dockerfile: Dockerfile
    platforms:
      - linux/amd64
