apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "lassie-bot-dog.fullname" . }}-config"
  labels:
    {{- include "lassie-bot-dog.labels" . | nindent 4 }}
data:
  GITLAB_URL: {{ default "" .Values.gitlab.url | quote }}
