apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "lassie-bot-dog.fullname" . }}-secret"
  labels:
    {{- include "lassie-bot-dog.labels" . | nindent 4 }}
data:
  GITLAB_TOKEN: {{ default "" .Values.gitlab.token | b64enc | quote }}
