name: Release

on:
  push:
    tags:
      - "*"
  pull_request:

jobs:
  go-releaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Login to ghcr.io registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - run: |
          echo "Releasing version '${GITHUB_REF#refs/*/}'' ..."

      - name: Run GoReleaser
        if: github.event_name != 'pull_request'
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: ${{ github.event_name == 'pull_request' && 'build --clean' || 'release --clean' }} # don't push on PRs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload assets
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v2
        with:
          name: lassie-bot-dog
          path: dist/*

      - name: Update helm chart versions
        run: |
          sed -i "s/<version>/${GITHUB_REF#refs/*/}/g" charts/lassie-bot-dog/Chart.yaml
          cat charts/lassie-bot-dog/Chart.yaml

      - name: Run chart-releaser
        if: github.event_name != 'pull_request'
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_RELEASE_NAME_TEMPLATE: "helm-{{ .Version }}"
